import { AdminPage } from '../components/admin-page'
import { withEditorId, withoutEditorId, type EditorIdentity } from '../editor-identity'
import { useCallback, useEffect, useState } from 'react'
import { useLatestRequest } from '../use-latest-request'
import { DndContext, PointerSensor, useDroppable, useSensor, useSensors, type DragEndEvent } from '@dnd-kit/core'
import { arrayMove, rectSortingStrategy, SortableContext, useSortable, verticalListSortingStrategy } from '@dnd-kit/sortable'
import { CSS } from '@dnd-kit/utilities'
import type { FriendLink, FriendLinkGroup, GooseAdminApi } from '@gooseforum/client'
import { Badge } from '@gooseforum/ui/components/badge'
import { Button } from '@gooseforum/ui/components/button'
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@gooseforum/ui/components/dialog'
import { Empty, EmptyHeader, EmptyMedia, EmptyTitle } from '@gooseforum/ui/components/empty'
import { Field, FieldDescription, FieldError, FieldGroup, FieldLabel } from '@gooseforum/ui/components/field'
import { Input } from '@gooseforum/ui/components/input'
import { Spinner } from '@gooseforum/ui/components/spinner'
import { Switch } from '@gooseforum/ui/components/switch'
import { ExternalLink, Eye, EyeOff, GripVertical, Link as LinkIcon, Pencil, Plus, RefreshCw, Send, ShieldCheck, Trash2 } from 'lucide-react'
import { toast } from 'sonner'
import type { PageConfigTextKey } from '../page-config-i18n'

type EditorLink = FriendLink & EditorIdentity
type EditorGroup = Omit<FriendLinkGroup, 'links'> & EditorIdentity & { links: EditorLink[] }

type Text = (key: PageConfigTextKey) => string
type GroupDialog = { mode: 'add' | 'edit'; index: number | null }
type LinkDialog = { mode: 'add' | 'edit'; groupIndex: number; linkIndex: number | null }
type DeleteTarget = { type: 'group' | 'link'; groupIndex: number; linkIndex?: number }

const colors = ['#3b82f6', '#22c55e', '#a855f7', '#64748b', '#ef4444', '#f97316', '#f59e0b', '#10b981', '#06b6d4', '#6366f1', '#8b5cf6', '#ec4899']
const emojis = ['🔗', '👥', '✍️', '📁', '⭐', '🔥', '💡', '🛠️', '🎨', '💬', '📢', '🏠', '🚀', '🎁']

export function LinksManagementPage({ api, text }: { api: GooseAdminApi; text: Text }) {
  const [groups, setGroups] = useState<EditorGroup[]>([])
  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState('')
  const [groupDialog, setGroupDialog] = useState<GroupDialog | null>(null)
  const [linkDialog, setLinkDialog] = useState<LinkDialog | null>(null)
  const [deleteTarget, setDeleteTarget] = useState<DeleteTarget | null>(null)
  const sensors = useSensors(useSensor(PointerSensor, { activationConstraint: { distance: 6 } }))

  const beginRequest = useLatestRequest();
  const load = useCallback(async () => { const isCurrent = beginRequest(); setLoading(true); setError(''); try { const result = await api.pages.links(); if (isCurrent()) setGroups(normalizeGroups(result)) } catch (reason) { if (isCurrent()) setError(errorMessage(reason, text('loadFailed'))) } finally { if (isCurrent()) setLoading(false) } }, [api, text, beginRequest]);
  useEffect(() => { void load() }, [load])
  async function persist(next: FriendLinkGroup[]) { const normalized = normalizeGroups(next); setGroups(normalized); setSaving(true); try { await api.pages.saveLinks(normalized.map(group => ({ ...withoutEditorId(group), links: group.links.map(withoutEditorId) }))); toast.success(text('saved')) } catch (reason) { toast.error(errorMessage(reason, text('saveFailed'))); await load() } finally { setSaving(false) } }

  function dragEnd(event: DragEndEvent) {
    if (saving) return
    const active = event.active.data.current as DragData | undefined
    const over = event.over?.data.current as DragData | undefined
    if (!active || !over) return
    if (active.type === 'group' && over.type === 'group' && active.groupIndex !== over.groupIndex) { void persist(arrayMove(groups, active.groupIndex, over.groupIndex)); return }
    if (active.type !== 'link' || (over.type !== 'link' && over.type !== 'link-container')) return
    const targetGroup = over.groupIndex
    if (active.groupIndex === targetGroup && over.type === 'link') { const next = normalizeGroups(groups); next[targetGroup].links = arrayMove(next[targetGroup].links, active.linkIndex, over.linkIndex); void persist(next); return }
    const next = normalizeGroups(groups); const [item] = next[active.groupIndex].links.splice(active.linkIndex, 1); if (!item) return
    const targetIndex = over.type === 'link' ? over.linkIndex : next[targetGroup].links.length
    next[targetGroup].links.splice(targetIndex, 0, item); void persist(next)
  }

  const total = groups.reduce((sum, group) => sum + group.links.length, 0)
  return <AdminPage><header className="flex items-center justify-between gap-3"><div><h2 className="text-lg font-semibold">{text('linksTitle')}</h2><p className="text-xs text-muted-foreground">{text('linksDescription')}</p></div><div className="flex gap-1.5"><Button variant="outline" size="sm" disabled={loading || saving} onClick={() => void load()}><RefreshCw data-icon="inline-start" className={loading ? 'animate-spin' : undefined} />{text('refresh')}</Button><Button size="sm" disabled={saving} onClick={() => setGroupDialog({ mode: 'add', index: null })}><Plus data-icon="inline-start" />{text('newGroup')}</Button></div></header>
    {loading && !groups.length ? <Empty className="min-h-48 border"><EmptyHeader><EmptyMedia variant="icon"><Spinner /></EmptyMedia><EmptyTitle>{text('loading')}</EmptyTitle></EmptyHeader></Empty> : error ? <div className="rounded-lg border border-destructive/30 p-3 text-sm text-destructive">{error}</div> : <DndContext sensors={sensors} onDragEnd={dragEnd}><div className="grid items-start gap-4 xl:grid-cols-[minmax(0,1fr)_260px]"><SortableContext items={groups.map(group => group.editorId)} strategy={verticalListSortingStrategy}><div className="flex flex-col gap-5 pb-6">{groups.map((group, index) => <SortableGroup key={group.editorId} id={group.editorId} group={group} groupIndex={index} text={text} saving={saving} onAdd={() => setLinkDialog({ mode: 'add', groupIndex: index, linkIndex: null })} onEdit={() => setGroupDialog({ mode: 'edit', index })} onDelete={() => setDeleteTarget({ type: 'group', groupIndex: index })} onEditLink={(linkIndex) => setLinkDialog({ mode: 'edit', groupIndex: index, linkIndex })} onDeleteLink={(linkIndex) => setDeleteTarget({ type: 'link', groupIndex: index, linkIndex })} onToggle={(linkIndex) => { if (saving) return; const next = normalizeGroups(groups); next[index].links[linkIndex].status = (next[index].links[linkIndex].status ?? 1) === 0 ? 1 : 0; void persist(next) }} />)}</div></SortableContext><aside className="flex flex-col gap-3"><Info title={text('linkGuide')}><p>{text('linkGuideText')}</p><Button asChild size="sm"><a href="/publish" target="_blank" rel="noreferrer"><Send data-icon="inline-start" />{text('openPublish')}</a></Button></Info><Info title={text('safety')}><p className="flex gap-2"><ShieldCheck className="mt-0.5 size-4 shrink-0" />{text('safety1')}</p><p className="flex gap-2"><ShieldCheck className="mt-0.5 size-4 shrink-0" />{text('safety2')}</p><p className="flex gap-2"><ShieldCheck className="mt-0.5 size-4 shrink-0" />{text('safety3')}</p></Info><Badge variant="secondary">{total} {text('totalLinks')}</Badge></aside></div></DndContext>}
    <GroupEditor dialog={groupDialog} group={groupDialog?.index != null ? groups[groupDialog.index] : undefined} saving={saving} text={text} onClose={() => setGroupDialog(null)} onSave={(value) => { const next = normalizeGroups(groups); if (groupDialog?.mode === 'add') next.push(withEditorId({ ...value, links: [] })); else if (groupDialog?.index != null) next[groupDialog.index] = { ...next[groupDialog.index], ...value }; setGroupDialog(null); void persist(next) }} />
    <LinkEditor dialog={linkDialog} link={linkDialog?.linkIndex != null ? groups[linkDialog.groupIndex]?.links[linkDialog.linkIndex] : undefined} saving={saving} text={text} onClose={() => setLinkDialog(null)} onSave={(value) => { if (!linkDialog) return; const next = normalizeGroups(groups); if (linkDialog.mode === 'add') next[linkDialog.groupIndex].links.push(withEditorId(value)); else if (linkDialog.linkIndex != null) next[linkDialog.groupIndex].links[linkDialog.linkIndex] = withEditorId({ ...value, editorId: next[linkDialog.groupIndex].links[linkDialog.linkIndex].editorId }); setLinkDialog(null); void persist(next) }} />
    <DeleteDialog target={deleteTarget} saving={saving} text={text} onClose={() => setDeleteTarget(null)} onConfirm={() => { if (!deleteTarget) return; const next = normalizeGroups(groups); if (deleteTarget.type === 'group') next.splice(deleteTarget.groupIndex, 1); else if (deleteTarget.linkIndex != null) next[deleteTarget.groupIndex].links.splice(deleteTarget.linkIndex, 1); setDeleteTarget(null); void persist(next) }} />
  </AdminPage>
}

type DragData = { type: 'group'; groupIndex: number } | { type: 'link'; groupIndex: number; linkIndex: number } | { type: 'link-container'; groupIndex: number }
function SortableGroup({ id, group, groupIndex, text, saving, onAdd, onEdit, onDelete, onEditLink, onDeleteLink, onToggle }: { id: string; group: EditorGroup; groupIndex: number; text: Text; saving: boolean; onAdd(): void; onEdit(): void; onDelete(): void; onEditLink(index: number): void; onDeleteLink(index: number): void; onToggle(index: number): void }) { const sortable = useSortable({ id, data: { type: 'group', groupIndex } satisfies DragData }); const style = { transform: CSS.Transform.toString(sortable.transform), transition: sortable.transition, opacity: sortable.isDragging ? .45 : 1 }; return <section ref={sortable.setNodeRef} style={style} className="flex flex-col gap-2.5"><header className="flex items-center justify-between gap-3 px-1 lg:px-0"><div className="flex min-w-0 items-center gap-2"><Button variant="ghost" size="icon-xs" className="cursor-grab text-muted-foreground" {...sortable.attributes} {...sortable.listeners}><GripVertical /></Button><span className="flex size-7 shrink-0 items-center justify-center rounded-lg bg-accent text-sm" style={{ color: group.color }}>{group.emoji || '↗'}</span><h3 className="truncate text-base font-bold">{group.name}</h3></div><div className="flex items-center gap-0.5"><Badge variant="secondary">{group.links.length}</Badge><Button variant="ghost" size="sm" onClick={onAdd}><Plus data-icon="inline-start" />{text('add')}</Button><Button variant="ghost" size="icon-sm" title={text('edit')} onClick={onEdit}><Pencil /></Button><Button variant="ghost" size="icon-sm" title={text('delete')} onClick={onDelete}><Trash2 /></Button></div></header><LinkContainer group={group} groupIndex={groupIndex} text={text} saving={saving} onAdd={onAdd} onEdit={onEditLink} onDelete={onDeleteLink} onToggle={onToggle} /></section> }
function LinkContainer({ group, groupIndex, text, onAdd, onEdit, onDelete, onToggle }: { group: EditorGroup; groupIndex: number; text: Text; saving: boolean; onAdd(): void; onEdit(index: number): void; onDelete(index: number): void; onToggle(index: number): void }) { const drop = useDroppable({ id: `link-container-${group.editorId}`, data: { type: 'link-container', groupIndex } satisfies DragData }); return <SortableContext items={group.links.map(link => link.editorId)} strategy={rectSortingStrategy}><div ref={drop.setNodeRef} className="grid auto-rows-min grid-cols-2 items-start gap-2 rounded-lg border border-dashed border-transparent lg:grid-cols-3 xl:grid-cols-4 2xl:grid-cols-5">{group.links.map((link, index) => <SortableLink key={link.editorId} id={link.editorId} link={link} groupIndex={groupIndex} linkIndex={index} text={text} onEdit={() => onEdit(index)} onDelete={() => onDelete(index)} onToggle={() => onToggle(index)} />)}{!group.links.length ? <Button variant="ghost" className="col-span-full h-24 border border-dashed font-normal text-muted-foreground" onClick={onAdd}><LinkIcon data-icon="inline-start" />{text('emptyGroup')}</Button> : null}</div></SortableContext> }
function SortableLink({ id, link, groupIndex, linkIndex, text, onEdit, onDelete, onToggle }: { id: string; link: FriendLink; groupIndex: number; linkIndex: number; text: Text; onEdit(): void; onDelete(): void; onToggle(): void }) { const sortable = useSortable({ id, data: { type: 'link', groupIndex, linkIndex } satisfies DragData }); return <article ref={sortable.setNodeRef} style={{ transform: CSS.Transform.toString(sortable.transform), transition: sortable.transition, opacity: sortable.isDragging ? .45 : link.status === 0 ? .6 : 1 }} className="group relative min-w-0 rounded-xl border bg-background p-2 transition-colors hover:border-primary/30 hover:bg-primary/5"><div className="flex items-center gap-2"><div className="flex size-8 shrink-0 items-center justify-center overflow-hidden rounded-lg border bg-muted">{link.logoUrl ? <img src={link.logoUrl} alt={link.name} className="size-full object-cover" /> : <LinkIcon className="size-4 text-muted-foreground" />}</div><div className="min-w-0 flex-1"><div className="flex min-w-0 items-center gap-1.5"><a href={link.url} target="_blank" rel="noreferrer" className="truncate text-[13px] font-semibold group-hover:text-primary">{link.name}</a><ExternalLink className="size-3 shrink-0 text-muted-foreground group-hover:text-primary" /></div><p className="mt-0.5 truncate text-[11px] leading-4 text-muted-foreground">{link.desc || link.url}</p></div></div><div className="absolute right-1 top-1 flex gap-0.5 rounded-md bg-background/95 p-0.5 opacity-0 shadow-sm ring-1 ring-border transition-opacity group-focus-within:opacity-100 group-hover:opacity-100"><Button variant="ghost" size="icon-xs" className="cursor-grab" {...sortable.attributes} {...sortable.listeners}><GripVertical /></Button><Button variant="ghost" size="icon-xs" title={text('visible')} onClick={onToggle}>{link.status === 0 ? <EyeOff /> : <Eye />}</Button><Button variant="ghost" size="icon-xs" title={text('edit')} onClick={onEdit}><Pencil /></Button><Button variant="ghost" size="icon-xs" title={text('delete')} onClick={onDelete}><Trash2 /></Button></div></article> }

function GroupEditor({ dialog, group, saving, text, onClose, onSave }: { dialog: GroupDialog | null; group?: FriendLinkGroup; saving: boolean; text: Text; onClose(): void; onSave(value: Pick<FriendLinkGroup, 'name' | 'emoji' | 'color'>): void }) { const [form, setForm] = useState({ name: '', emoji: '🔗', color: '#3b82f6' }); const [error, setError] = useState(''); useEffect(() => { if (dialog) { setForm({ name: group?.name || '', emoji: group?.emoji || '🔗', color: group?.color || '#3b82f6' }); setError('') } }, [dialog, group]); return <Dialog open={Boolean(dialog)} onOpenChange={(open) => !open && onClose()}><DialogContent><DialogHeader><DialogTitle>{dialog?.mode === 'edit' ? text('edit') : text('newGroup')}</DialogTitle><DialogDescription>{text('groupHint')}</DialogDescription></DialogHeader><form id="group-form" onSubmit={(event) => { event.preventDefault(); if (!form.name.trim()) { setError(text('requiredGroup')); return } onSave({ ...form, name: form.name.trim() }) }}><FieldGroup><Field data-invalid={Boolean(error)}><FieldLabel>{text('groupName')}</FieldLabel><Input autoFocus aria-invalid={Boolean(error)} value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /><FieldError>{error}</FieldError></Field><div className="grid grid-cols-2 gap-3"><Field><FieldLabel>{text('emoji')}</FieldLabel><Input value={form.emoji} onChange={(event) => setForm({ ...form, emoji: event.target.value })} /></Field><Field><FieldLabel>{text('color')}</FieldLabel><Input type="color" value={form.color} onChange={(event) => setForm({ ...form, color: event.target.value })} /></Field></div><div className="flex flex-wrap gap-1">{emojis.map((emoji) => <Button key={emoji} type="button" variant="ghost" size="icon-sm" onClick={() => setForm({ ...form, emoji })}>{emoji}</Button>)}</div><div className="flex flex-wrap gap-1">{colors.map((color) => <Button key={color} type="button" variant="ghost" size="icon-sm" aria-label={color} className="rounded-full border" style={{ backgroundColor: color }} onClick={() => setForm({ ...form, color })} />)}</div></FieldGroup></form><DialogFooter><Button variant="outline" onClick={onClose}>{text('cancel')}</Button><Button form="group-form" type="submit" disabled={saving}>{saving ? <Spinner data-icon="inline-start" /> : null}{text('save')}</Button></DialogFooter></DialogContent></Dialog> }
function LinkEditor({ dialog, link, saving, text, onClose, onSave }: { dialog: LinkDialog | null; link?: FriendLink; saving: boolean; text: Text; onClose(): void; onSave(value: FriendLink): void }) { const [form, setForm] = useState<FriendLink>({ name: '', url: '', desc: '', logoUrl: '', status: 1 }); const [error, setError] = useState(''); useEffect(() => { if (dialog) { setForm({ name: link?.name || '', url: link?.url || '', desc: link?.desc || '', logoUrl: link?.logoUrl || '', status: link?.status ?? 1 }); setError('') } }, [dialog, link]); return <Dialog open={Boolean(dialog)} onOpenChange={(open) => !open && onClose()}><DialogContent><DialogHeader><DialogTitle>{dialog?.mode === 'edit' ? text('edit') : text('add')}</DialogTitle><DialogDescription>{text('linkHint')}</DialogDescription></DialogHeader><form id="link-form" onSubmit={(event) => { event.preventDefault(); if (!form.name.trim() || !form.url.trim()) { setError(text('requiredLink')); return } onSave({ ...form, name: form.name.trim(), url: form.url.trim() }) }}><FieldGroup><Field data-invalid={Boolean(error)}><FieldLabel>{text('linkName')}</FieldLabel><Input autoFocus aria-invalid={Boolean(error)} value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /><FieldError>{error}</FieldError></Field><Field><FieldLabel>{text('url')}</FieldLabel><Input value={form.url} onChange={(event) => setForm({ ...form, url: event.target.value })} placeholder="https://…" /></Field><Field><FieldLabel>{text('description')}</FieldLabel><Input value={form.desc} onChange={(event) => setForm({ ...form, desc: event.target.value })} /></Field><Field><FieldLabel>{text('logoUrl')}</FieldLabel><Input value={form.logoUrl} onChange={(event) => setForm({ ...form, logoUrl: event.target.value })} /></Field><Field orientation="horizontal"><div className="flex-1"><FieldLabel>{text('visible')}</FieldLabel><FieldDescription>{text('visibleHint')}</FieldDescription></div><Switch checked={form.status !== 0} onCheckedChange={(checked) => setForm({ ...form, status: checked ? 1 : 0 })} /></Field></FieldGroup></form><DialogFooter><Button variant="outline" onClick={onClose}>{text('cancel')}</Button><Button form="link-form" type="submit" disabled={saving}>{saving ? <Spinner data-icon="inline-start" /> : null}{text('save')}</Button></DialogFooter></DialogContent></Dialog> }
function DeleteDialog({ target, saving, text, onClose, onConfirm }: { target: DeleteTarget | null; saving: boolean; text: Text; onClose(): void; onConfirm(): void }) { const group = target?.type === 'group'; return <Dialog open={Boolean(target)} onOpenChange={(open) => !open && onClose()}><DialogContent><DialogHeader><DialogTitle>{group ? text('deleteGroup') : text('deleteLink')}</DialogTitle><DialogDescription>{group ? text('deleteGroupHint') : text('deleteLinkHint')}</DialogDescription></DialogHeader><DialogFooter><Button variant="outline" onClick={onClose}>{text('cancel')}</Button><Button variant="destructive" disabled={saving} onClick={onConfirm}><Trash2 data-icon="inline-start" />{text('delete')}</Button></DialogFooter></DialogContent></Dialog> }
function Info({ title, children }: { title: string; children: React.ReactNode }) { return <section className="flex flex-col gap-3 rounded-xl border bg-background p-4 text-sm leading-6 text-muted-foreground"><h3 className="font-semibold text-foreground">{title}</h3>{children}</section> }
function normalizeGroups(value: FriendLinkGroup[] | null | undefined): EditorGroup[] { return Array.isArray(value) ? value.map(group => withEditorId({ ...group, links: Array.isArray(group.links) ? group.links.map(withEditorId) : [] })) : [] }
function errorMessage(reason: unknown, fallback: string) { return reason instanceof Error && reason.message ? reason.message : fallback }
